/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    kotlin("jvm")
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo1.maven.org/maven2/")
    }
    mavenCentral()
}

dependencies {
    api(libs.org.seleniumhq.selenium.selenium.java)
    api(libs.ch.qos.logback.logback.classic)
    api(libs.com.sksamuel.hoplite.hoplite.core)
    api(libs.com.sksamuel.hoplite.hoplite.yaml)
    implementation(kotlin("stdlib-jdk8"))
}

group = "it.alesc"
version = "0.0.1-SNAPSHOT"
description = "selenium"

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.named<Test>("test") {
    useTestNG()
}
kotlin {
    jvmToolchain(8)
}